Create_time = '2022-09-27T15:53:49.154343607Z'
Result_ID = '7341617480923334298'

[Result_output]
[Result_output.AREA]
KAA = 808.13
KAB = 18.96
KAC = 83.32
KAD = 33.0
KAE = 115.58
KAF = 41.19
KAG = 36.68
KAH = 102.94
KAI = 50.14
KAJ = 32.3
KAK = 19.27
KAL = 39.11
KAM = 29.54
KAN = 29.18
KAO = 13.17

[Result_output.RESIDUES]
KAA = [['291', 'A', 'L'], ['37', 'A', 'K'], ['41', 'A', 'F'], ['94', 'A', 'R'], ['98', 'A', 'Y'], ['108', 'A', 'D'], ['111', 'A', 'C'], ['112', 'A', 'R'], ['114', 'A', 'M'], ['115', 'A', 'S'], ['118', 'A', 'L'], ['119', 'A', 'Y'], ['123', 'A', 'Y'], ['127', 'A', 'Y'], ['165', 'A', 'L'], ['166', 'A', 'I'], ['169', 'A', 'S'], ['170', 'A', 'S'], ['172', 'A', 'M'], ['173', 'A', 'L'], ['176', 'A', 'S'], ['179', 'A', 'E'], ['180', 'A', 'Q'], ['186', 'A', 'S'], ['187', 'A', 'C'], ['188', 'A', 'L'], ['189', 'A', 'E'], ['190', 'A', 'L'], ['191', 'A', 'N'], ['194', 'A', 'K'], ['198', 'A', 'L'], ['201', 'A', 'M'], ['202', 'A', 'N'], ['204', 'A', 'I'], ['205', 'A', 'A'], ['208', 'A', 'V'], ['209', 'A', 'G'], ['263', 'A', 'Y'], ['267', 'A', 'R'], ['270', 'A', 'H'], ['271', 'A', 'L'], ['274', 'A', 'W'], ['278', 'A', 'L'], ['279', 'A', 'C'], ['280', 'A', 'K'], ['284', 'A', 'H'], ['287', 'A', 'L'], ['288', 'A', 'V']]
KAB = [['272', 'A', 'T'], ['202', 'A', 'N'], ['203', 'A', 'Y'], ['206', 'A', 'L'], ['268', 'A', 'T'], ['271', 'A', 'L']]
KAC = [['1101', 'A', 'Y'], ['1006', 'A', 'N'], ['1037', 'A', 'A'], ['1040', 'A', 'A'], ['1058', 'A', 'M'], ['1061', 'A', 'F'], ['1062', 'A', 'R'], ['1065', 'A', 'F'], ['1068', 'A', 'L'], ['1094', 'A', 'L'], ['1097', 'A', 'T'], ['1098', 'A', 'R']]
KAD = [['1098', 'A', 'R'], ['1006', 'A', 'N'], ['1009', 'A', 'T'], ['1010', 'A', 'L'], ['1013', 'A', 'N'], ['1033', 'A', 'M'], ['1036', 'A', 'A'], ['1037', 'A', 'A'], ['1065', 'A', 'F']]
KAE = [['310', 'A', 'E'], ['71', 'A', 'T'], ['72', 'A', 'S'], ['73', 'A', 'V'], ['135', 'A', 'V'], ['136', 'A', 'R'], ['139', 'A', 'A'], ['140', 'A', 'M'], ['143', 'A', 'P'], ['151', 'A', 'S'], ['1104', 'A', 'K'], ['240', 'A', 'V'], ['241', 'A', 'S'], ['244', 'A', 'K'], ['245', 'A', 'A']]
KAF = [['163', 'A', 'W'], ['83', 'A', 'S'], ['86', 'A', 'L'], ['87', 'A', 'F'], ['117', 'A', 'S'], ['120', 'A', 'V'], ['121', 'A', 'N']]
KAG = [['132', 'A', 'L'], ['76', 'A', 'F'], ['77', 'A', 'M'], ['80', 'A', 'L'], ['128', 'A', 'F'], ['129', 'A', 'L']]
KAH = [['298', 'A', 'A'], ['84', 'A', 'N'], ['87', 'A', 'F'], ['118', 'A', 'L'], ['121', 'A', 'N'], ['122', 'A', 'M'], ['125', 'A', 'S'], ['260', 'A', 'F'], ['294', 'A', 'A'], ['295', 'A', 'A'], ['297', 'A', 'N']]
KAI = [['1094', 'A', 'L'], ['1014', 'A', 'L'], ['1017', 'A', 'I'], ['1030', 'A', 'L'], ['1033', 'A', 'M'], ['1069', 'A', 'V'], ['1072', 'A', 'I'], ['1091', 'A', 'A']]
KAJ = [['1091', 'A', 'A'], ['1017', 'A', 'I'], ['1026', 'A', 'V'], ['1030', 'A', 'L'], ['1072', 'A', 'I'], ['1087', 'A', 'A'], ['1088', 'A', 'Q']]
KAK = [['315', 'A', 'R'], ['63', 'A', 'F'], ['74', 'A', 'N'], ['78', 'A', 'L']]
KAL = [['1088', 'A', 'Q'], ['1017', 'A', 'I'], ['1023', 'A', 'A'], ['1026', 'A', 'V'], ['1076', 'A', 'L'], ['1084', 'A', 'V'], ['1087', 'A', 'A']]
KAM = [['295', 'A', 'A'], ['45', 'A', 'Y'], ['87', 'A', 'F'], ['91', 'A', 'L'], ['94', 'A', 'R'], ['118', 'A', 'L']]
KAN = [['313', 'A', 'K'], ['243', 'A', 'R'], ['244', 'A', 'K'], ['305', 'A', 'Y'], ['306', 'A', 'Y'], ['307', 'A', 'F'], ['308', 'A', 'A'], ['309', 'A', 'G'], ['310', 'A', 'E'], ['312', 'A', 'F']]
KAO = [['102', 'A', 'S'], ['34', 'A', 'E'], ['37', 'A', 'K'], ['38', 'A', 'R'], ['98', 'A', 'Y']]

[Result_output.VOLUME]
KAA = 1036.15
KAB = 9.07
KAC = 106.49
KAD = 22.9
KAE = 111.67
KAF = 40.61
KAG = 17.28
KAH = 84.46
KAI = 23.76
KAJ = 16.85
KAK = 10.15
KAL = 31.97
KAM = 12.31
KAN = 18.14
KAO = 6.7

[Result_param]
[Result_param.cutoffs]
ligand_cutoff = 5.0
removal_distance = 2.4
volume_cutoff = 5.0

[Result_param.internalbox]
[Result_param.internalbox.p1]
x = -4.0
y = -4.0
z = -4.0

[Result_param.internalbox.p2]
x = 4.0
y = -4.0
z = -4.0

[Result_param.internalbox.p3]
x = -4.0
y = 4.0
z = -4.0

[Result_param.internalbox.p4]
x = -4.0
y = -4.0
z = 4.0

[Result_param.modes]
box_mode = false
kvp_mode = false
ligand_mode = false
resolution_mode = 'Low'
surface_mode = true
whole_protein_mode = true

[Result_param.probes]
probe_in = 1.4
probe_out = 4.0

[Result_param.step_size]
step_size = 0.0

[Result_param.visiblebox]
[Result_param.visiblebox.p1]
x = 0.0
y = 0.0
z = 0.0

[Result_param.visiblebox.p2]
x = 0.0
y = 0.0
z = 0.0

[Result_param.visiblebox.p3]
x = 0.0
y = 0.0
z = 0.0

[Result_param.visiblebox.p4]
x = 0.0
y = 0.0
z = 0.0
